const _ = require('underscore')

export const isFirefox = self.InstallTrigger
export const isSafari = Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor') > 0
export const isIE = /*@cc_on!@*/false || !!document.documentMode
export const isEdge = !isIE && !!self.StyleMedia
export const isChrome = !!self.chrome && !!window.chrome.webstore
export const isBlink = isChrome && !!window.CSS
export const isMicrosoftWindows = navigator.userAgent.indexOf('Windows') >= 0

export const HumanRelationship = {
  '': 'None selected',
  single: 'Single',
  in: 'In a relationship',
  engaged: 'Engaged',
  married: 'Married',
  love: 'In love',
  complex: 'It\'s complicated',
  search: 'Actively searching'
}

export const Languages = [
  {id: 0, iso: 'ru', name: 'Русский'},
  {id: 3, iso: 'en', name: 'English'}
]

export const emoji = {
  '😃': ['Smile', ':)', ':-)'],
  '😄': ['Laugh', ':D', ':-D'],
  '😉': ['Blink', ')', '-)'],
  '😍': 'In Love',
  '😘': 'Love Kiss',
  '😚': 'Kiss',
  '😳': 'Surprised',
  '😌': 'Joy',
  '😜': ['Blink Tongue', ':P', ':-P'],
  '😝': ['Tongue', 'XD', 'X-D'],
  '😒': ['Sad', ':(', ':-('],
  // '😏': 'Tricky',
  '😓': 'Busy',
  '😞': 'Sad',
  '😥': ['Tear', ':\'-(', ':\'(', '(', '-(', '=('],
  '😭': 'Cry',
  '😡': ['Angry'],
  '😷': 'Silent',
  '👿': 'Evil',
  '👽': 'Stranger',
  '💘': 'Heart',
  '🌟': 'Star',
  '🎵': 'Music',
  '🔥': 'Fire',
  '👍': 'Like',
  '👎': 'Dislike',
  '👌': 'Good',
  '👊': 'Beet',
  // '✌': '',
  '💋': 'Lips',
  '🙏': 'Pray',
  // '☝': '',
  '👏': 'Pop',
  '💪': 'Power',
  '🔒': 'Lock',
  '🔓': 'Unlock',
  '🔑': 'Key',
  '💰': 'Money',
  '🚬': 'Smoke',
  '💣': 'Bomb',
  '🔫': 'Kill',
  '💊': 'Pill',
  '💉': 'Prick',
  '⚽': 'Ball',
  '🎯': 'Target',
  '🏆': 'Award',
  '🎩': 'Hat',
  '💄': 'Pomade',
  '💎': 'Diamond',
  // '☕': '',
  '🍹': 'Cocktail',
  '🍺': 'Beer',
  '🍴': 'Eat',
  '🍭': 'Candy',
  '🍦': 'Ice'
}

export const code = {
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  MOVED_TEMPORARILY: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  REQUEST_TOO_LONG: 413,
  REQUEST_URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  REQUESTED_RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  INSUFFICIENT_SPACE_ON_RESOURCE: 419,
  METHOD_FAILURE: 420,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  INSUFFICIENT_STORAGE: 507,
  NETWORK_AUTHENTICATION_REQUIRED: 511
}

export const EmptyKeys = [' ', '\n', '\t', '\xa0', 'Meta', 'Alt', 'Control', 'Shift', 'CapsLock', 'ArrowLeft', 'ArrowRight']

export const t13n = {
  'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'j',
  'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u', 'ф': 'f',
  'х': 'kh', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'shch', 'ъ': '', 'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu',
  'я': 'ya', '_': '_', 'ї': 'yi', 'ґ': 'g', 'є': 'ie', 'і': 'i'
}

export const Sex = {
  male: 'Male',
  female: 'Female'
}

export const twilio = {
  INVALID_NUMBER: 21211
}

const _countries = [
  {iso: 'AF', code: 93, flag: '🇦🇫', id: 30},
  {iso: 'AL', code: 355, flag: '🇦🇱', id: 21},
  {iso: 'DZ', code: 213, flag: '🇩🇿', id: 22},
  {iso: 'AS', code: 1684},
  {iso: 'AD', code: 376, flag: '🇦🇩', id: 26},
  {iso: 'AO', code: 244, flag: '🇦🇴', id: 25},
  {iso: 'AI', code: 1264, flag: '🇦🇮', id: 24},
  {iso: 'AQ', flag: '🇦🇶'},
  {iso: 'AG', code: 1268, flag: '🇦🇬', id: 27},
  {iso: 'AR', code: 54, flag: '🇦🇷', id: 28},
  {iso: 'AM', code: 374, flag: '🇦🇲', id: 6},
  {iso: 'AW', code: 297, flag: '🇦🇼', id: 29},
  {iso: 'AU', code: 61, flag: '🇦🇺', id: 19},
  {iso: 'AT', code: 43, flag: '🇦🇹', id: 20},
  {iso: 'AZ', code: 994, flag: '🇦🇿', id: 5},
  {iso: 'BS', code: 1242, flag: '🇧🇸', id: 31},
  {iso: 'BH', code: 973, flag: '🇧🇭', id: 34},
  {iso: 'BD', code: 880, flag: '🇧🇩', id: 32},
  {iso: 'BB', code: 1246, flag: '🇧🇧', id: 33},
  {iso: 'BY', code: 375, flag: '🇧🇾', id: 3},
  {iso: 'BE', code: 32, flag: '🇧🇪', id: 36},
  {iso: 'BZ', code: 501, flag: '🇧🇿', id: 35},
  {iso: 'BJ', code: 229, flag: '🇧🇯', id: 37},
  {iso: 'BM', code: 1441, flag: '🇧🇲', id: 38},
  {iso: 'BT', code: 975, flag: '🇧🇹', id: 47},
  {iso: 'BO', code: 591},
  {iso: 'BA', code: 387, flag: '🇧🇦', id: 41},
  {iso: 'BW', code: 267, flag: '🇧🇼', id: 42},
  {iso: 'BR', code: 55, flag: '🇧🇷', id: 43},
  {iso: 'IO', code: 246, flag: '🇮🇴'},
  {iso: 'BN', code: 673, id: 44},
  {iso: 'BG', code: 359, flag: '🇧🇬', id: 39},
  {iso: 'BF', code: 226, flag: '🇧🇫', id: 45},
  {iso: 'BI', code: 257, flag: '🇧🇮', id: 46},
  {iso: 'KH', code: 855, flag: '🇰🇭', id: 91},
  {iso: 'CM', code: 237, flag: '🇨🇲', id: 92},
  {iso: 'CA', code: 1, flag: '🇨🇦', id: 10},
  {iso: 'CV', code: 238, flag: '🇨🇻', id: 90},
  {iso: 'KY', code: 345, flag: '🇰🇾', id: 149},
  {iso: 'CF', code: 236, flag: '🇨🇫', id: 213},
  {iso: 'TD', code: 235, flag: '🇹🇩', id: 214},
  {iso: 'CL', code: 56, flag: '🇨🇱', id: 216},
  {iso: 'CN', code: 86, flag: '🇨🇳', id: 97},
  {iso: 'CX', code: 61, flag: '🇨🇽'},
  {iso: 'CC', code: 61},
  {iso: 'CO', code: 57, flag: '🇨🇴', id: 98},
  {iso: 'KM', code: 269, flag: '🇰🇲', id: 99},
  {iso: 'CG', code: 242, id: 100},
  {iso: 'CD', code: 243},
  {iso: 'CK', code: 682, flag: '🇨🇰', id: 150},
  {iso: 'CR', code: 506, flag: '🇨🇷', id: 102},
  {iso: 'CI', code: 225},
  {iso: 'HR', code: 385, flag: '🇭🇷', id: 212},
  {iso: 'CU', code: 53, flag: '🇨🇺', id: 104},
  {iso: 'CY', code: 537, flag: '🇨🇾', id: 95},
  {iso: 'CZ', code: 420, flag: '🇨🇿', id: 215},
  {iso: 'DK', code: 45, flag: '🇩🇰', id: 73},
  {iso: 'DJ', code: 253, flag: '🇩🇯', id: 231},
  {iso: 'DM', code: 1767, flag: '🇩🇲', id: 74},
  {iso: 'DO', code: 1849, flag: '🇩🇴', id: 75},
  {iso: 'EC', code: 593, flag: '🇪🇨', id: 221},
  {iso: 'EG', code: 20, flag: '🇪🇬', id: 76},
  {iso: 'SV', code: 503, flag: '🇸🇻', id: 166},
  {iso: 'GQ', code: 240, flag: '🇬🇶', id: 222},
  {iso: 'ER', code: 291, flag: '🇪🇷', id: 223},
  {iso: 'EE', code: 372, flag: '🇪🇪', id: 14},
  {iso: 'ET', code: 251, flag: '🇪🇹', id: 224},
  {iso: 'FK', code: 500},
  {iso: 'FO', code: 298, flag: '🇫🇴', id: 204},
  {iso: 'FJ', code: 679, flag: '🇫🇯', id: 205},
  {iso: 'FI', code: 358, flag: '🇫🇮', id: 207},
  {iso: 'FR', code: 33, flag: '🇫🇷', id: 209},
  {iso: 'GF', code: 594, flag: '🇬🇫', id: 210},
  {iso: 'PF', code: 689, flag: '🇵🇫', id: 211},
  {iso: 'GA', code: 241, flag: '🇬🇦', id: 56},
  {iso: 'GM', code: 220, flag: '🇬🇲', id: 59},
  {iso: 'GE', code: 995, flag: '🇬🇪', id: 7},
  {iso: 'DE', code: 49, flag: '🇩🇪', id: 65},
  {iso: 'GH', code: 233, flag: '🇬🇭', id: 60},
  {iso: 'GI', code: 350, flag: '🇬🇮', id: 66},
  {iso: 'GR', code: 30, flag: '🇬🇷', id: 71},
  {iso: 'GL', code: 299, flag: '🇬🇱', id: 70},
  {iso: 'GD', code: 1473, flag: '🇬🇩', id: 69},
  {iso: 'GP', code: 590, flag: '🇬🇵', id: 61},
  {iso: 'GU', code: 1671, flag: '🇬🇺', id: 72},
  {iso: 'GT', code: 502, flag: '🇬🇹', id: 62},
  {iso: 'GG', code: 44, flag: '🇬🇬', id: 236},
  {iso: 'GN', code: 224, flag: '🇬🇳', id: 63},
  {iso: 'GW', code: 245, flag: '🇬🇼', id: 64},
  {iso: 'GY', code: 595, flag: '🇬🇾', id: 58},
  {iso: 'HT', code: 509, flag: '🇭🇹', id: 57},
  {iso: 'VA', code: 379},
  {iso: 'HN', code: 504, flag: '🇭🇳', id: 67},
  {iso: 'HK', code: 852, flag: '🇭🇰', id: 68},
  {iso: 'HU', code: 36, flag: '🇭🇺', id: 50},
  {iso: 'IS', code: 354, flag: '🇮🇸', id: 86},
  {iso: 'IN', code: 91, flag: '🇮🇳', id: 80},
  {iso: 'ID', code: 62, flag: '🇮🇩', id: 81},
  {iso: 'IR', code: 98, id: 84},
  {iso: 'IQ', code: 964, flag: '🇮🇶', id: 83},
  {iso: 'IE', code: 353, flag: '🇮🇪', id: 85},
  {iso: 'IM', code: 44, flag: '🇮🇲', id: 147},
  {iso: 'IL', code: 972, flag: '🇮🇱', id: 8},
  {iso: 'IT', code: 39, flag: '🇮🇹', id: 88},
  {iso: 'JM', code: 1876, flag: '🇯🇲', id: 228},
  {iso: 'JP', code: 81, flag: '🇯🇵', id: 229},
  {iso: 'JE', code: 44, flag: '🇯🇪', id: 237},
  {iso: 'JO', code: 962, flag: '🇯🇴', id: 82},
  {iso: 'KZ', code: 77, flag: '🇰🇿', id: 4},
  {iso: 'KE', code: 254, flag: '🇰🇪', id: 94},
  {iso: 'KI', code: 686, flag: '🇰🇮', id: 96},
  {iso: 'KP', code: 850},
  {iso: 'KR', code: 82},
  {iso: 'KW', code: 965, flag: '🇰🇼', id: 105},
  {iso: 'KG', code: 996, flag: '🇰🇬', id: 11},
  {iso: 'LA', code: 856},
  {iso: 'LV', code: 371, flag: '🇱🇻', id: 12},
  {iso: 'LB', code: 961, flag: '🇱🇧', id: 109},
  {iso: 'LS', code: 266, flag: '🇱🇸', id: 107},
  {iso: 'LR', code: 231, flag: '🇱🇷', id: 108},
  {iso: 'LY', code: 218},
  {iso: 'LI', code: 423, flag: '🇱🇮', id: 111},
  {iso: 'LT', code: 370, flag: '🇱🇹', id: 13},
  {iso: 'LU', code: 352, flag: '🇱🇺', id: 112},
  {iso: 'MO', code: 853},
  {iso: 'MK', code: 389},
  {iso: 'MG', code: 261, flag: '🇲🇬', id: 115},
  {iso: 'MW', code: 265, flag: '🇲🇼', id: 118},
  {iso: 'MY', code: 60, flag: '🇲🇾', id: 119},
  {iso: 'MV', code: 960, flag: '🇲🇻', id: 121},
  {iso: 'ML', code: 223, flag: '🇲🇱', id: 120},
  {iso: 'MT', code: 356, flag: '🇲🇹', id: 122},
  {iso: 'MH', code: 692, flag: '🇲🇭', id: 125},
  {iso: 'MQ', code: 596, flag: '🇲🇶', id: 124},
  {iso: 'MR', code: 222, flag: '🇲🇷', id: 114},
  {iso: 'MU', code: 230, flag: '🇲🇺', id: 113},
  {iso: 'YT', code: 262, flag: '🇾🇹'},
  {iso: 'MX', code: 52, flag: '🇲🇽', id: 126},
  {iso: 'FM', code: 691},
  {iso: 'MD', code: 373},
  {iso: 'MC', code: 377, flag: '🇲🇨', id: 129},
  {iso: 'MN', code: 976, flag: '🇲🇳', id: 130},
  {iso: 'ME', code: 382, flag: '🇲🇪', id: 230},
  {iso: 'MS', code: 1664, flag: '🇲🇸', id: 131},
  {iso: 'MA', code: 212, flag: '🇲🇦', id: 123},
  {iso: 'MZ', code: 258, flag: '🇲🇿', id: 128},
  {iso: 'MM', code: 95, flag: '🇲🇲', id: 132},
  {iso: 'NA', code: 264, flag: '🇳🇦', id: 133},
  {iso: 'NR', code: 674, flag: '🇳🇷', id: 134},
  {iso: 'NP', code: 977, flag: '🇳🇵', id: 135},
  {iso: 'NL', code: 31, flag: '🇳🇱', id: 139},
  {iso: 'AN', code: 599},
  {iso: 'NC', code: 687, flag: '🇳🇨', id: 143},
  {iso: 'NZ', code: 64, flag: '🇳🇿', id: 142},
  {iso: 'NI', code: 505, flag: '🇳🇮', id: 140},
  {iso: 'NE', code: 227, flag: '🇳🇪', id: 136},
  {iso: 'NG', code: 234, flag: '🇳🇬', id: 137},
  {iso: 'NU', code: 683, flag: '🇳🇺', id: 141},
  {iso: 'NF', code: 672, flag: '🇳🇫', id: 148},
  {iso: 'MP', code: 1670, flag: '🇲🇵', id: 174},
  {iso: 'NO', code: 47, flag: '🇳🇴', id: 144},
  {iso: 'OM', code: 968, flag: '🇴🇲', id: 146},
  {iso: 'PK', code: 92, flag: '🇵🇰', id: 152},
  {iso: 'PW', code: 680, flag: '🇵🇼', id: 153},
  {iso: 'PS', code: 970},
  {iso: 'PA', code: 507, flag: '🇵🇦', id: 155},
  {iso: 'PG', code: 675, flag: '🇵🇬', id: 156},
  {iso: 'PY', code: 595, flag: '🇵🇾', id: 157},
  {iso: 'PE', code: 51, flag: '🇵🇪', id: 158},
  {iso: 'PH', code: 63, flag: '🇵🇭', id: 206},
  {iso: 'PN', code: 872},
  {iso: 'PL', code: 48, flag: '🇵🇱', id: 160},
  {iso: 'PT', code: 351, flag: '🇵🇹', id: 161},
  {iso: 'PR', code: 1939, flag: '🇵🇷', id: 162},
  {iso: 'QA', code: 974, flag: '🇶🇦', id: 93},
  {iso: 'RO', code: 40, flag: '🇷🇴', id: 165},
  {iso: 'RU', code: 7, flag: '🇷🇺', id: 1},
  {iso: 'RW', code: 250, flag: '🇷🇼', id: 164},
  {iso: 'RE', code: 262, flag: '🇷🇪', id: 163},
  {iso: 'BL', code: 590},
  {iso: 'SH', code: 290},
  {iso: 'KN', code: 1869, id: 178},
  {iso: 'LC', code: 1758, id: 179},
  {iso: 'MF', code: 590},
  {iso: 'PM', code: 508, id: 180},
  {iso: 'VC', code: 1784, id: 177},
  {iso: 'WS', code: 685, flag: '🇼🇸', id: 167},
  {iso: 'SM', code: 378, flag: '🇸🇲', id: 168},
  {iso: 'ST', code: 239},
  {iso: 'SA', code: 966, flag: '🇸🇦', id: 170},
  {iso: 'SN', code: 221, flag: '🇸🇳', id: 176},
  {iso: 'RS', code: 381, flag: '🇷🇸', id: 181},
  {iso: 'SC', code: 248, flag: '🇸🇨', id: 175},
  {iso: 'SL', code: 232, flag: '🇸🇱', id: 190},
  {iso: 'SG', code: 65, flag: '🇸🇬', id: 182},
  {iso: 'SK', code: 421, flag: '🇸🇰', id: 184},
  {iso: 'SI', code: 386, flag: '🇸🇮', id: 185},
  {iso: 'SB', code: 677, flag: '🇸🇧', id: 186},
  {iso: 'SO', code: 252, flag: '🇸🇴', id: 187},
  {iso: 'ZA', code: 27, flag: '🇿🇦', id: 227},
  {iso: 'GS', code: 500},
  {iso: 'ES', code: 34, flag: '🇪🇸', id: 87},
  {iso: 'LK', code: 94, flag: '🇱🇰', id: 220},
  {iso: 'SD', code: 249, flag: '🇸🇩', id: 188},
  {iso: 'SR', code: 597, flag: '🇸🇷', id: 189},
  {iso: 'SJ', code: 47, flag: '🇸🇯', id: 219},
  {iso: 'SZ', code: 268, flag: '🇸🇿', id: 171},
  {iso: 'SE', code: 46, flag: '🇸🇪', id: 218},
  {iso: 'CH', code: 41, flag: '🇨🇭', id: 217},
  {iso: 'SY', code: 963},
  {iso: 'TW', code: 886},
  {iso: 'TJ', code: 992, flag: '🇹🇯', id: 16},
  {iso: 'TZ', code: 255},
  {iso: 'TH', code: 66, flag: '🇹🇭', id: 191},
  {iso: 'TL', code: 670, flag: '🇹🇱'},
  {iso: 'TG', code: 228, flag: '🇹🇬', id: 194},
  {iso: 'TK', code: 690, flag: '🇹🇰', id: 195},
  {iso: 'TO', code: 676, flag: '🇹🇴', id: 196},
  {iso: 'TT', code: 1868, flag: '🇹🇹', id: 197},
  {iso: 'TN', code: 216, flag: '🇹🇳', id: 199},
  {iso: 'TR', code: 90, flag: '🇹🇷', id: 200},
  {iso: 'TM', code: 993, flag: '🇹🇲', id: 17},
  {iso: 'TC', code: 1649, flag: '🇹🇨', id: 151},
  {iso: 'TV', code: 688, flag: '🇹🇻', id: 198},
  {iso: 'UG', code: 256, flag: '🇺🇬', id: 201},
  {iso: 'UA', code: 380, flag: '🇺🇦', id: 2},
  {iso: 'AE', code: 971, flag: '🇦🇪', id: 145},
  {iso: 'GB', code: 44, flag: '🇬🇧', id: 49},
  {iso: 'US', code: 1, flag: '🇺🇸'},
  {iso: 'UY', code: 598, flag: '🇺🇾', id: 203},
  {iso: 'UZ', code: 998, flag: '🇺🇿', id: 18},
  {iso: 'VU', code: 678, flag: '🇻🇺', id: 48},
  {iso: 'VE', code: 58},
  {iso: 'VN', code: 84},
  {iso: 'VG', code: 1284},
  {iso: 'VI', code: 1340},
  {iso: 'WF', code: 681, flag: '🇼🇫', id: 202},
  {iso: 'YE', code: 967, flag: '🇾🇪', id: 89},
  {iso: 'ZM', code: 260, flag: '🇿🇲', id: 77},
  {iso: 'ZW', code: 263, flag: '🇿🇼', id: 79},
  {iso: 'AX'}
]

export const countries = []
export const countryCodes = []

export function register(target, events) {
  _.each(events, function (event, key) {
    target.addEventListener(key, event)
  })
}

_.each(emoji, function (object, chararcter) {
  if ('string' === typeof object) {
    object = {
      title: object
    }
  }
  else {
    object = {
      title: object[0],
      shortcuts: object.slice(1)
    }
  }
  emoji[chararcter] = object
  object.name = object.title.toLowerCase().replace(/\s+/g, '_')
})
Object.freeze(emoji)

_countries.forEach(function (country) {
  if (country.id && country.flag && country.code) {
    countries.push(country)
    countryCodes.push(country.code)
  }
})

countryCodes.sort(function (a, b) {
  return b - a
})

Object.freeze(countries)
Object.freeze(countryCodes)
Object.freeze(HumanRelationship)
Object.freeze(Languages)
Object.freeze(code)
Object.freeze(Sex)
